version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 9099:8080
    volumes:
      - /home:/data
      - ./config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
